<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="a2d9c312-0bc1-493a-8de9-9bcc2bf5d8c0" name="Huyoucai@HUYOUCAI-PC 2014-07-20 22:41:01" runUser="Huyoucai-PC\Huyoucai" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="e4167082-9d56-471a-b488-96ac36bacfa7">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="Huyoucai_HUYOUCAI-PC 2014-07-20 22_41_01">
      <DeploymentItem filename="G:\GitHub\Algorithm-Recursion-Dynamic\Algorithm-Recursion\bin\Debug\Algorithm-Recursion.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2014-07-20T22:41:01.9974816-06:00" queuing="2014-07-20T22:41:04.9746519-06:00" start="2014-07-20T22:41:05.2126655-06:00" finish="2014-07-20T22:49:28.4574495-06:00" />
  <ResultSummary outcome="Error">
    <Counters total="1" executed="1" error="0" failed="0" timeout="0" aborted="1" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
    <RunInfos>
      <RunInfo computerName="HUYOUCAI-PC" outcome="Error" timestamp="2014-07-20T22:49:28.4564494-06:00">
        <Text>Test host process exited unexpectedly.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="Concatenation2Test" storage="g:\github\algorithm-recursion-dynamic\testproject\bin\debug\testproject.dll" id="64f1280f-e459-9ed0-160d-9af9d616f971">
      <Execution id="b53c1483-d3ba-4e20-9ea4-63f83058f743" />
      <TestMethod codeBase="G:/GitHub/Algorithm-Recursion-Dynamic/TestProject/bin/Debug/TestProject.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="TestProject.RecursionTest, TestProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="Concatenation2Test" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="64f1280f-e459-9ed0-160d-9af9d616f971" executionId="b53c1483-d3ba-4e20-9ea4-63f83058f743" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="b53c1483-d3ba-4e20-9ea4-63f83058f743" testId="64f1280f-e459-9ed0-160d-9af9d616f971" testName="Concatenation2Test" computerName="HUYOUCAI-PC" duration="00:08:23.0517729" startTime="2014-07-20T22:41:05.4056766-06:00" endTime="2014-07-20T22:49:28.4574495-06:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Aborted" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="b53c1483-d3ba-4e20-9ea4-63f83058f743">
    </UnitTestResult>
  </Results>
</TestRun>