<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="09f050ea-9ce3-4380-b42f-a58ab9f7ab03" name="Huyoucai@HUYOUCAI-PC 2014-07-20 16:07:26" runUser="Huyoucai-PC\Huyoucai" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="e4167082-9d56-471a-b488-96ac36bacfa7">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="Huyoucai_HUYOUCAI-PC 2014-07-20 16_07_26">
      <DeploymentItem filename="G:\GitHub\Algorithm-Recursion-Dynamic\Algorithm-Recursion\bin\Debug\Algorithm-Recursion.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2014-07-20T16:07:26.4833649-06:00" queuing="2014-07-20T16:07:28.2504660-06:00" start="2014-07-20T16:07:28.3894739-06:00" finish="2014-07-20T16:08:38.4764827-06:00" />
  <ResultSummary outcome="Error">
    <Counters total="1" executed="1" error="0" failed="0" timeout="0" aborted="1" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
    <RunInfos>
      <RunInfo computerName="HUYOUCAI-PC" outcome="Error" timestamp="2014-07-20T16:08:38.4734825-06:00">
        <Text>Test host process exited unexpectedly.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="ConcatenationTest" storage="g:\github\algorithm-recursion-dynamic\testproject\bin\debug\testproject.dll" id="aa32e834-b8c6-a44e-3c96-67df6682ce00">
      <Execution id="72b577d5-52e4-43c3-90eb-3b1779ad2f73" />
      <TestMethod codeBase="G:/GitHub/Algorithm-Recursion-Dynamic/TestProject/bin/Debug/TestProject.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="TestProject.RecursionTest, TestProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="ConcatenationTest" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="aa32e834-b8c6-a44e-3c96-67df6682ce00" executionId="72b577d5-52e4-43c3-90eb-3b1779ad2f73" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="72b577d5-52e4-43c3-90eb-3b1779ad2f73" testId="aa32e834-b8c6-a44e-3c96-67df6682ce00" testName="ConcatenationTest" computerName="HUYOUCAI-PC" duration="00:01:09.9630017" startTime="2014-07-20T16:07:28.5134810-06:00" endTime="2014-07-20T16:08:38.4764827-06:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Aborted" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="72b577d5-52e4-43c3-90eb-3b1779ad2f73">
    </UnitTestResult>
  </Results>
</TestRun>