<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="5b8209d7-0fca-4a69-bad3-6db2b2a46d3f" name="Huyoucai@HUYOUCAI-PC 2014-07-20 21:52:13" runUser="Huyoucai-PC\Huyoucai" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="e4167082-9d56-471a-b488-96ac36bacfa7">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="Huyoucai_HUYOUCAI-PC 2014-07-20 21_52_13">
      <DeploymentItem filename="G:\GitHub\Algorithm-Recursion-Dynamic\Algorithm-Recursion\bin\Debug\Algorithm-Recursion.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2014-07-20T21:52:13.5009812-06:00" queuing="2014-07-20T21:52:20.7053933-06:00" start="2014-07-20T21:52:20.9064048-06:00" finish="2014-07-20T21:52:33.1021023-06:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="Concatenation2Test" storage="g:\github\algorithm-recursion-dynamic\testproject\bin\debug\testproject.dll" id="64f1280f-e459-9ed0-160d-9af9d616f971">
      <Execution id="c8067660-07fe-4294-9ff1-a66ede63d606" />
      <TestMethod codeBase="G:/GitHub/Algorithm-Recursion-Dynamic/TestProject/bin/Debug/TestProject.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="TestProject.RecursionTest, TestProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="Concatenation2Test" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="64f1280f-e459-9ed0-160d-9af9d616f971" executionId="c8067660-07fe-4294-9ff1-a66ede63d606" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="c8067660-07fe-4294-9ff1-a66ede63d606" testId="64f1280f-e459-9ed0-160d-9af9d616f971" testName="Concatenation2Test" computerName="HUYOUCAI-PC" duration="00:00:09.8549782" startTime="2014-07-20T21:52:21.0854150-06:00" endTime="2014-07-20T21:52:32.7330812-06:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="c8067660-07fe-4294-9ff1-a66ede63d606">
      <Output>
        <ErrorInfo>
          <Message>Test method TestProject.RecursionTest.Concatenation2Test threw exception: 
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.</Message>
          <StackTrace>    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ClassLibrary.Recursion.Concatenation2(String s, String[] words) in G:\GitHub\Algorithm-Recursion-Dynamic\Algorithm-Recursion\Recursion.cs:line 2025
   at TestProject.RecursionTest.Concatenation2Test() in G:\GitHub\Algorithm-Recursion-Dynamic\TestProject\RecursionTest.cs:line 671
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>